server:
  port: 8080
  servlet:
    context-path: /department

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/department_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ""

