server:
  port: 8081
  servlet:
    context-path: /employee

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/employee_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ""

